version: '3.8'

services:
  # API Node.js
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: minio-api
    environment:
      - NODE_ENV=production
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
    depends_on:
      - minio
    networks:
      - minio-network

  # Frontend Vue.js
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: minio-frontend
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - minio-network

  # MinIO
  minio:
    image: minio/minio:latest
    container_name: minio-server
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    networks:
      - minio-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: minio-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - api
    networks:
      - minio-network

volumes:
  minio-data:

networks:
  minio-network:
    driver: bridge
