version: '3.8'

services:
  # API Node.js
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: minio-api-dev
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
    depends_on:
      - minio
    networks:
      - minio-network

  # Frontend Vue.js
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: minio-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - minio-network

  # MinIO
  minio:
    image: minio/minio:latest
    container_name: minio-server-dev
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    networks:
      - minio-network

volumes:
  minio-data:

networks:
  minio-network:
    driver: bridge
